### ISSUE TITLE
Mistyping of the service name in the manifest file 

### ISSUE THREAD

**Issue by PhilippeComte** [watson-developer-cloud/tradeoff-analytics-nodejs#48]
Here is the current name of the service in the manifest file
```yml
- services:
  - tradeoff-analytics-service-standard
  name: tradeoff-analytics-demo
```
it should be :  -tradeoff-analytics-standard-service
